/**
 * Render all graph demo examples to dist/graphs/ (.dot, .svg, index.html).
 *
 * Usage: pnpm graphs   (from apps/playground or monorepo root via make graphs)
 */
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadGraphviz, renderDot } from "@chordlang/graph";
import manifest from "../../../examples/manifest.json" with { type: "json" };

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const REPO = join(ROOT, "../..");
const GRAPHS = join(REPO, "examples/graphs");
const OUT = join(ROOT, "dist", "graphs");

function galleryHTML(entries: { name: string; slug: string; svg: string }[]): string {
  const cards = entries
    .map(
      ({ name, slug, svg }) => `  <section class="card">
    <h2>${name}</h2>
    <div class="graph">${svg}</div>
    <p class="files"><a href="${slug}.dot">${slug}.dot</a> · <a href="${slug}.svg">${slug}.svg</a></p>
  </section>`,
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>chordlang — graph examples</title>
<style>
@font-face {
  font-family: "ChordFont";
  src: url("../../public/fonts/ChordFont-Real Book.ttf") format("truetype");
}
* { box-sizing: border-box; margin: 0; }
body {
  font-family: system-ui, sans-serif;
  background: #1a1d21;
  color: #e8e6e1;
  padding: 2rem;
}
h1 { font-size: 1.2rem; font-weight: 600; margin-bottom: 0.3rem; }
p.meta { font-size: 0.8rem; color: #8a8f96; margin-bottom: 1.5rem; }
.grid { display: grid; gap: 1.25rem; }
.card {
  background: #fbf8f1;
  color: #1a1815;
  border-radius: 6px;
  padding: 1.2rem 1.4rem 1rem;
}
.card h2 { font-size: 0.85rem; font-weight: 600; margin-bottom: 0.8rem; }
.graph {
  overflow: auto;
  display: flex;
  justify-content: center;
  padding: 0.5rem 0;
}
.graph svg { max-width: 100%; height: auto; }
.graph text {
  font-family: "ChordFont", ui-sans-serif !important;
  font-feature-settings: "liga" 1, "calt" 1;
  fill: #1a1815;
}
.files {
  font-family: ui-monospace, Menlo, monospace;
  font-size: 0.68rem;
  color: #6f6a5e;
  margin-top: 0.6rem;
}
.files a { color: inherit; }
.files a:hover { color: #a8823c; }
</style>
</head>
<body>
<h1>chordlang — graph examples</h1>
<p class="meta">${entries.length} graphs · ChordFont node labels · generated by <code>make graphs</code></p>
<div class="grid">
${cards}
</div>
</body>
</html>`;
}

async function main() {
  await mkdir(OUT, { recursive: true });

  const graphviz = await loadGraphviz();
  const entries: { name: string; slug: string; svg: string }[] = [];

  for (const { file, label } of manifest.graphs) {
    const dot = (await readFile(join(GRAPHS, `${file}.cfgv`), "utf8")).trimEnd();
    const svg = renderDot(graphviz, dot);

    await writeFile(join(OUT, `${file}.dot`), dot, "utf8");
    await writeFile(join(OUT, `${file}.svg`), svg, "utf8");
    entries.push({ name: label, slug: file, svg });
    console.log(`  ${file}.dot`);
    console.log(`  ${file}.svg`);
  }

  await writeFile(join(OUT, "index.html"), galleryHTML(entries), "utf8");
  console.log("  index.html");
  console.log(`\nWrote ${entries.length} graphs to ${OUT}`);
  console.log(`Open: ${join(OUT, "index.html")}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
